Some more edits for ch.7
mjavascript/practical-es6 pull request #16
Opened 2016-12-28 21:31 UTC by schindld

-Not sure if there's a better option for lines 1422/1424. The console returns [Object, Object].
-I found line 1483 confusing. Not sure how to word it better. Basically trying to say that all three parameters are 0-based indices, and the 3rd parameter goes up to but doesn't include that index.

2016-12-28 22:12 UTC, bevacqua requested changes

2016-12-28 22:12 UTC, bevacqua commented on chapters/ch07.asciidoc
> +// <- [Object, Object]
Maybe we should extract the `apple` and `onion` to variables by those names, then reference the variables in the comment, for clarity?

2016-12-28 22:12 UTC, bevacqua commented on chapters/ch07.asciidoc
> +The function call shown below takes the +items+ array and determines that it'll start "pasting" items in the sixth position (zero-based). It further determines that the items to be copied will be tak
Let's remove the second and third mentions of `zero-based`. In the last bit we could probably get away with `third position (not inclusive)`

2016-12-28 22:28 UTC, schindld commented on chapters/ch07.asciidoc
> +The function call shown below takes the +items+ array and determines that it'll start "pasting" items in the sixth position (zero-based). It further determines that the items to be copied will be tak
Sounds good

2016-12-28 22:29 UTC, schindld commented on chapters/ch07.asciidoc
> +// <- [Object, Object]
What do you mean? `Array.from(things, thing => thing.name)` would give `['Apple', 'Onion']`, but would be a bit redundant. But I don't think that's what you mean. Can you give me an example?

2016-12-28 22:32 UTC, bevacqua commented on chapters/ch07.asciidoc
> +// <- [Object, Object]
I meant

```js
const apple = {
  ...
}
const onion = {
  ...
}
const groceries = {
  0: apple,
  1: onion,
  length: 2
}
Array.from(groceries)
// <- [apple, onion]
Array.from(groceries, grocery => grocery.name)
// <- ['Apple', 'Onion']
```

2016-12-28 22:40 UTC, schindld commented on chapters/ch07.asciidoc
> +// <- [Object, Object]
`Array.from(groceries)` still gives `[Object, Object]`.
How about  going back to the current `things` and I change line 1421 to `const [apple, onion] = Array.from(things)`, followed by `console.log(apple.name)` and `// <- "Apple"`?

2016-12-28 22:42 UTC, bevacqua commented on chapters/ch07.asciidoc
> +// <- [Object, Object]
It does, but we are showing that the resulting array contains the same object reference as the `groceries` object does. Using destructuring here wouldn't show that

2016-12-29 00:42 UTC, schindld commented
No problem. Also accidentally left groceries out. It's in now.

2016-12-29 00:43 UTC, merged

2016-12-29 00:43 UTC, bevacqua commented
Thanks again! :tada: